version: '3'

services:
  keycloak-next:
    build: .
    # entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    command: sh ./.docker/entrypoint.sh
